### ISSUE TITLE
Error <br>

### ISSUE THREAD

**Issue by exeto** [rajdee/posthtml-bem#13]
**node**: 4.2.1

``` html
<div block="block">
  <br>
</div>
```

```
TypeError: Cannot read property 'elem' of undefined
    at /Users/exeto/Projects/test/node_modules/posthtml-bem/index.js:137:55
    at Array.forEach (native)
    at /Users/exeto/Projects/test/node_modules/posthtml-bem/index.js:136:30
    at /Users/exeto/Projects/test/node_modules/posthtml/lib/api.js:61:51
    at /Users/exeto/Projects/test/node_modules/posthtml/lib/api.js:24:20
    at traverse (/Users/exeto/Projects/test/node_modules/posthtml/lib/api.js:71:32)
    at Array.walk (/Users/exeto/Projects/test/node_modules/posthtml/lib/api.js:23:9)
    at Array.match (/Users/exeto/Projects/test/node_modules/posthtml/lib/api.js:60:19)
    at posthtmlBem (/Users/exeto/Projects/test/node_modules/posthtml-bem/index.js:130:14)
    at err (/Users/exeto/Projects/test/node_modules/posthtml/lib/posthtml.js:117:24)
```

**Comment by voischev** [comment]
@exeto :+1:
